async:
  url: https://github.com/socketry/async
  command: bundle exec bake test
async-dns:
  url: https://github.com/socketry/async-dns
  command: CONSOLE_LEVEL=debug bundle exec rspec
falcon:
  url: https://github.com/socketry/falcon
  command: CONSOLE_LEVEL=debug bundle exec sus
console-adapter-rails:
  url: https://github.com/socketry/console-adapter-rails
  command: CONSOLE_LEVEL=debug bundle exec sus
console-adapter-sidekiq:
  url: https://github.com/socketry/console-adapter-sidekiq
  command: CONSOLE_LEVEL=debug bundle exec sus
console-adapter-datadog:
  url: https://github.com/socketry/console-output-datadog
  command: CONSOLE_LEVEL=debug bundle exec sus

